language: node_js

cache:
  directories:
    - "node_modules"

node_js:
  - "8"

install:
  - npm install -g yarn
  - yarn install

script:
  - yarn test

before_deploy:
  - yarn build
  - touch out/.nojekyll

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: out
  keep-history: true
  target-branch: master
  fqdn: opensource.ebates.com
  on:
    branch: develop
